"""
Multi-format export service.
Generates PDF, DOCX, HTML, JSON, and CSV from answer data.
"""
import csv
import io
import json


def _display_answer(answer: dict) -> str:
    if answer.get("user_edited") and answer.get("edited_answer"):
        return answer["edited_answer"]
    return answer.get("generated_answer") or "Not present in the document"


def _format_citations(citations: list) -> str:
    if not citations:
        return ""
    return " | ".join(
        f'[{i+1}] {c.get("doc_name", "")} — "{c.get("excerpt", "")}"'
        for i, c in enumerate(citations)
    )


# ─── JSON Export ─────────────────────────────────────────────────────────────

def export_json(answers: list[dict], coverage: dict | None, project_name: str) -> bytes:
    payload = {
        "project": project_name,
        "coverage": coverage,
        "answers": [
            {
                "question_number": a["question_number"],
                "question_text": a["question_text"],
                "answer": _display_answer(a),
                "confidence_score": a.get("confidence_score"),
                "not_found": a.get("not_found", False),
                "user_edited": a.get("user_edited", False),
                "citations": a.get("citations") or [],
                "evidence_snippets": a.get("evidence_snippets") or [],
                "all_candidates": a.get("answer_candidates") or [],
            }
            for a in answers
        ],
    }
    return json.dumps(payload, indent=2, default=str).encode("utf-8")


# ─── CSV Export ──────────────────────────────────────────────────────────────

def export_csv(answers: list[dict]) -> bytes:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "Question #", "Question Text", "Answer",
        "Confidence Score", "Not Found", "User Edited", "Citations",
    ])
    for a in answers:
        writer.writerow([
            a["question_number"],
            a["question_text"],
            _display_answer(a),
            f"{round((a.get('confidence_score') or 0) * 100)}%",
            "Yes" if a.get("not_found") else "No",
            "Yes" if a.get("user_edited") else "No",
            _format_citations(a.get("citations") or []),
        ])
    return output.getvalue().encode("utf-8-sig")  # BOM for Excel


# ─── HTML Export ─────────────────────────────────────────────────────────────

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{project_name} — Questionnaire Answers</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 860px; margin: 40px auto; padding: 0 24px; color: #1A1A1A; }}
  h1 {{ color: #5B4B8A; margin-bottom: 4px; }}
  .meta {{ color: #666; font-size: 14px; margin-bottom: 40px; }}
  .qa {{ background: #fff; border: 1px solid #E0E0E0; border-radius: 8px; padding: 20px; margin-bottom: 16px; }}
  .qnum {{ display: inline-block; background: #F5F0FF; color: #5B4B8A; border-radius: 50%; width: 28px; height: 28px; line-height: 28px; text-align: center; font-weight: bold; font-size: 13px; margin-right: 8px; vertical-align: middle; }}
  .qtext {{ font-weight: 600; }}
  .answer {{ color: #333; line-height: 1.7; margin: 12px 0; font-size: 15px; }}
  .not-found {{ color: #F39C12; font-style: italic; }}
  .citations {{ margin-top: 12px; padding: 12px; background: #FAFAFA; border-radius: 6px; border: 1px solid #E0E0E0; }}
  .citations h4 {{ font-size: 12px; text-transform: uppercase; color: #999; margin: 0 0 8px; }}
  .citation {{ font-size: 13px; color: #555; margin-bottom: 6px; }}
  .citation .doc {{ color: #5B4B8A; font-weight: 600; }}
  .confidence {{ font-size: 12px; color: #27AE60; margin-top: 4px; }}
</style>
</head>
<body>
<h1>{project_name}</h1>
<p class="meta">Generated by QuestionnaireAI · {answer_count} questions</p>
{body}
</body>
</html>"""


def export_html(answers: list[dict], project_name: str) -> bytes:
    items = []
    for a in answers:
        display = _display_answer(a).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        answer_class = "answer not-found" if a.get("not_found") else "answer"
        confidence_html = ""
        if not a.get("not_found") and a.get("confidence_score"):
            confidence_html = f'<div class="confidence">Confidence: {round(a["confidence_score"] * 100)}%</div>'

        cits = a.get("citations") or []
        cit_items = "".join(
            f'<div class="citation"><span class="doc">[{i+1}] {c.get("doc_name", "")}</span> — <em>&ldquo;{c.get("excerpt", "")}&rdquo;</em></div>'
            for i, c in enumerate(cits)
        )
        citations_html = f'<div class="citations"><h4>Citations</h4>{cit_items}</div>' if cits else ""

        q_text = a["question_text"].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        items.append(f"""
<div class="qa">
  <div style="margin-bottom:8px"><span class="qnum">{a['question_number']}</span><span class="qtext">{q_text}</span></div>
  <div class="{answer_class}">{display}</div>
  {confidence_html}
  {citations_html}
</div>""")

    html = _HTML_TEMPLATE.format(
        project_name=project_name,
        answer_count=len(answers),
        body="\n".join(items),
    )
    return html.encode("utf-8")


# ─── DOCX Export ─────────────────────────────────────────────────────────────

def export_docx(answers: list[dict], project_name: str) -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor

    doc = Document()
    title = doc.add_heading(project_name, level=0)
    title.runs[0].font.color.rgb = RGBColor(0x5B, 0x4B, 0x8A)
    doc.add_paragraph(f"Generated by QuestionnaireAI — {len(answers)} questions")

    for a in answers:
        heading = doc.add_paragraph()
        heading.add_run(f"Q{a['question_number']}: {a['question_text']}").bold = True

        display = _display_answer(a)
        a_para = doc.add_paragraph(display)
        if a.get("not_found"):
            a_para.runs[0].font.color.rgb = RGBColor(0xF3, 0x9C, 0x12)
            a_para.runs[0].italic = True

        if not a.get("not_found") and a.get("confidence_score"):
            cp = doc.add_paragraph(f"Confidence: {round(a['confidence_score'] * 100)}%")
            cp.runs[0].font.size = Pt(10)
            cp.runs[0].font.color.rgb = RGBColor(0x27, 0xAE, 0x60)

        cits = a.get("citations") or []
        if cits:
            ch = doc.add_paragraph("Citations:")
            ch.runs[0].bold = True
            ch.runs[0].font.size = Pt(10)
            for i, c in enumerate(cits):
                cp2 = doc.add_paragraph(
                    f'[{i+1}] {c.get("doc_name", "")} — "{c.get("excerpt", "")}"',
                    style="List Bullet",
                )
                cp2.runs[0].font.size = Pt(9)

        doc.add_paragraph("")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ─── PDF Export ──────────────────────────────────────────────────────────────

def export_pdf(answers: list[dict], project_name: str) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, HRFlowable

    PURPLE = colors.HexColor("#5B4B8A")
    GRAY = colors.HexColor("#666666")
    ORANGE = colors.HexColor("#F39C12")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=20*mm, rightMargin=20*mm,
                            topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()

    title_s = ParagraphStyle("T", parent=styles["Heading1"], textColor=PURPLE, fontSize=18, spaceAfter=4)
    meta_s = ParagraphStyle("M", parent=styles["Normal"], textColor=GRAY, fontSize=10, spaceAfter=12)
    q_s = ParagraphStyle("Q", parent=styles["Normal"], fontSize=11, fontName="Helvetica-Bold",
                          spaceBefore=12, spaceAfter=4)
    a_s = ParagraphStyle("A", parent=styles["Normal"], fontSize=10, leading=16, spaceAfter=4)
    nf_s = ParagraphStyle("NF", parent=a_s, textColor=ORANGE, fontName="Helvetica-Oblique")

    story = [
        Paragraph(project_name, title_s),
        Paragraph(f"Generated by QuestionnaireAI — {len(answers)} questions", meta_s),
        HRFlowable(width="100%", thickness=1, color=PURPLE, spaceAfter=8),
    ]

    for a in answers:
        display = _display_answer(a).replace("<", "&lt;").replace(">", "&gt;")
        edited = " (edited)" if a.get("user_edited") else ""
        story.append(Paragraph(f"Q{a['question_number']}: {a['question_text']}{edited}", q_s))
        story.append(Paragraph(display, nf_s if a.get("not_found") else a_s))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                color=colors.HexColor("#E0E0E0"), spaceAfter=4))

    doc.build(story)
    return buf.getvalue()
